### ISSUE TITLE
Add syntax highlighting as in GFM

### ISSUE THREAD

**Issue by bethrezen** [yiigist/www#3]
In Github flavored markdown we can specify language for code block.
Yiigist doesn't highlight language-specific keywords.
For example see http://yiigist.com/package/yii2mod/yii2-tree#?tab=readme
The code block 'Usage' specifies php language https://raw.githubusercontent.com/yii2mod/yii2-tree/master/README.md

**Comment by rmrevin** [comment]
This functionality is in the queue. Future versions will be added to all. We will report in this task.

**Comment by rmrevin** [comment]
You may tell the parser to GFM? We use now https://github.com/erusev/parsedown . 
But he does not code highlighting. Solution from github https://github.com/github/markup also not highlighted code. Moreover, we have tested, and he did wrong parse the readme file.

**Comment by rmrevin** [comment]
Added highlightjs.
Thanks.
